# Generated by Django 2.2.4 on 2019-08-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('update_date', models.DateTimeField(blank=True)),
            ],
            options={
                'get_latest_by': 'update_date',
            },
        ),
    ]
